[package]
name = "cimpler"
version = "0.1.0"
authors = ["Dylan Maccora <maccora17@gmail.com>"]

[dependencies]
reqwest = "0.4.0"
serde = "1.0"
serde_yaml = "0.7"
serde_derive = "1.0.2"
log = "0.3"
error-chain = "0.10"
git2 = "0.6.6"
zip = "0.2.5"
url = "1.4"
